/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import HealthClub.HealthSystem;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import HealthClub.Patient;

/**
 *
 * @author ruthwiksoudry
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    HealthSystem system;
    
    public ViewJPanel(HealthSystem system) {
        this.system = system;
        initComponents();
        addMockData();
    }
    
        private void addMockData() {
        
        //adding patients records into the table
        DefaultTableModel tableModel = (DefaultTableModel) tblModel.getModel();
        tableModel.setRowCount(0);
        
        //loop to display the patient information
        system.getPatientDirectory().forEach(patient -> {
            Object [] tableRow = new Object[10];
            tableRow[0] = patient.getPersonId();
            tableRow[1] = patient.getFirstName()+" "+patient.getLastName();
            tableRow[2] = patient.getDateOfBirth().toString();
            tableRow[3] = patient.getAgeGroup().toString();
            tableRow[5] = patient.getResidence().getHouseNumber();
            tableRow[6] = patient.getResidence().getCommunityName();
            tableRow[4] = patient.getResidence().getCity();
            tableModel.addRow(tableRow);
            
        });        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblModel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAbnormal = new javax.swing.JTable();
        txtDel = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 223, 225));

        tblModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PATIENT ID", "FULL NAME", "DOB", "AGE GROUP", "CITY", "HOUSE NUMBER", "COMMUNITY"
            }
        ));
        jScrollPane1.setViewportView(tblModel);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Click to View Abnormal Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblAbnormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COMMUNITY", "COUNT", "VITAL SIGN"
            }
        ));
        jScrollPane2.setViewportView(tblAbnormal);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setText("Delete Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("View Patient Details");

        jLabel2.setText("Enter Person Id :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HashMap diplayAbnormalBPByCommunity =  system.displayPatientsByAbnormalBP();
        HashMap diplayAbnormalHRByCommunity =  system.displayPatientsByAbnormalHR();
        
        DefaultTableModel tableModel = (DefaultTableModel) tblAbnormal.getModel();
        tableModel.setRowCount(0);

        //loop to display the abnormal heart rate patient 
        diplayAbnormalHRByCommunity.forEach((key, value) -> {
            Object [] tableRow = new Object[10];
            tableRow[0] = key;
            tableRow[1] = value;
            tableRow[2] = "HeartRate";
            tableModel.addRow(tableRow);
        });
        
        //loop to display the abnormal blood pressure patient 
        diplayAbnormalBPByCommunity.forEach((key, value) -> {
            Object [] tableRow = new Object[10];
            tableRow[0] = key;
            tableRow[1] = value;
            tableRow[2] = "BP";
            tableModel.addRow(tableRow);
        });
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //logic to delete the selected patient Id
        int selectedPatientId = Integer.parseInt(txtDel.getText());
        Patient selectedPatient = system.getPatientById(selectedPatientId);
        system.removePatient(selectedPatient);
        addMockData();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAbnormal;
    private javax.swing.JTable tblModel;
    private javax.swing.JTextField txtDel;
    // End of variables declaration//GEN-END:variables
    
}
